# Generated by Django 4.2.1 on 2025-10-14 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shouhin',
            fields=[
                ('hontai_num', models.AutoField(primary_key=True, serialize=False, verbose_name='本体No')),
                ('place', models.CharField(max_length=255, verbose_name='拠点')),
                ('hinban', models.CharField(max_length=255, verbose_name='品番')),
                ('hinmei', models.CharField(blank=True, max_length=255, null=True, verbose_name='品名')),
                ('color', models.CharField(blank=True, max_length=255, null=True, verbose_name='カラー')),
                ('size', models.CharField(max_length=255, verbose_name='サイズ')),
                ('size_num', models.IntegerField(default=0, verbose_name='サイズ値')),
                ('available', models.IntegerField(default=0, verbose_name='発注可能数')),
                ('keep', models.IntegerField(default=0, verbose_name='キープ数')),
                ('stock', models.IntegerField(default=0, verbose_name='在庫数')),
                ('tana', models.CharField(blank=True, max_length=255, null=True, verbose_name='棚番')),
                ('cost_price', models.IntegerField(default=0, verbose_name='原価')),
                ('bikou', models.CharField(blank=True, max_length=255, null=True, verbose_name='備考')),
                ('attention', models.CharField(blank=True, max_length=255, null=True, verbose_name='注意事項')),
                ('create_day', models.CharField(blank=True, max_length=255, null=True, verbose_name='登録日')),
                ('jan_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='JANコード')),
                ('sys_stock', models.IntegerField(default=0, verbose_name='システム在庫')),
                ('sys_order', models.IntegerField(default=0, verbose_name='システム発注')),
            ],
        ),
    ]
