# Generated by Django 4.2.1 on 2025-10-14 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaiko', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shouhin',
            name='hontai_num',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='本体No'),
        ),
    ]
