# Generated by Django 4.2.1 on 2025-10-14 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaiko', '0002_alter_shouhin_hontai_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shouhin',
            old_name='hinmei',
            new_name='shouhin_name',
        ),
        migrations.RenameField(
            model_name='shouhin',
            old_name='hinban',
            new_name='shouhin_num',
        ),
        migrations.AddField(
            model_name='shouhin',
            name='shouhin_set',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='品番 + 品名'),
        ),
    ]
