# Generated by Django 4.2.1 on 2025-10-15 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaiko', '0003_rename_hinmei_shouhin_shouhin_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=255, verbose_name='拠点')),
                ('show', models.IntegerField(default=0, verbose_name='営業に表示')),
            ],
        ),
    ]
