# Generated by Django 4.2.1 on 2025-10-21 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaiko', '0004_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shozoku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shozoku', models.CharField(max_length=30, verbose_name='所属')),
            ],
        ),
    ]
