# Generated by Django 4.2.1 on 2025-10-23 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaiko', '0005_shozoku'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_num', models.IntegerField(verbose_name='順番')),
                ('size', models.CharField(blank=True, max_length=255, verbose_name='サイズ')),
            ],
        ),
    ]
