# Generated by Django 4.2.1 on 2025-11-06 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaiko', '0006_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Irai_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('irai_num', models.IntegerField(default=0, verbose_name='依頼No')),
                ('hontai_num', models.IntegerField(default=0, verbose_name='本体No')),
                ('place', models.CharField(max_length=255, verbose_name='拠点')),
                ('shouhin_num', models.CharField(max_length=255, verbose_name='品番')),
                ('shouhin_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='品名')),
                ('color', models.CharField(blank=True, max_length=255, null=True, verbose_name='カラー')),
                ('size', models.CharField(max_length=255, verbose_name='サイズ')),
                ('size_num', models.IntegerField(default=0, verbose_name='サイズ値')),
                ('tana', models.CharField(blank=True, max_length=255, null=True, verbose_name='棚番')),
                ('kazu', models.IntegerField(default=0, verbose_name='数量')),
            ],
        ),
        migrations.CreateModel(
            name='Irai_list',
            fields=[
                ('irai_num', models.IntegerField(primary_key=True, serialize=False, verbose_name='依頼No')),
                ('irai_day', models.DateTimeField(auto_now_add=True, verbose_name='依頼日')),
                ('shozoku', models.CharField(blank=True, max_length=255, null=True, verbose_name='所属')),
                ('tantou', models.CharField(blank=True, max_length=255, null=True, verbose_name='担当者')),
                ('irai_type', models.IntegerField(default=0, verbose_name='依頼内容')),
                ('irai_status', models.IntegerField(default=0, verbose_name='状態')),
                ('hassou_type', models.IntegerField(default=0, verbose_name='発送タイプ')),
                ('hassou_day', models.DateField(blank=True, default=None, null=True, verbose_name='発送日')),
                ('zaiko_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='在庫出荷_商品')),
                ('zaiko_kakouba', models.CharField(blank=True, max_length=255, null=True, verbose_name='在庫出荷_加工場/店舗')),
                ('zaiko_gara', models.CharField(blank=True, max_length=255, null=True, verbose_name='在庫出荷_柄名')),
                ('zaiko_cus', models.CharField(blank=True, max_length=255, null=True, verbose_name='在庫出荷_顧客名')),
                ('zaiko_system', models.CharField(blank=True, max_length=255, null=True, verbose_name='在庫出荷_システム発送日')),
                ('keep_cus', models.CharField(blank=True, max_length=255, null=True, verbose_name='キープ_顧客名')),
                ('catalog_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='カタログ_発送先')),
                ('catalog_tempo', models.CharField(blank=True, max_length=255, null=True, verbose_name='カタログ_店舗名')),
                ('catalog_cus_com', models.CharField(blank=True, max_length=255, null=True, verbose_name='カタログ_会社名')),
                ('catalog_cus_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='カタログ_氏名')),
                ('catalog_cus_yubin', models.CharField(blank=True, max_length=255, null=True, verbose_name='カタログ_郵便番号')),
                ('catalog_cus_pref', models.CharField(blank=True, max_length=255, null=True, verbose_name='カタログ_都道府県')),
                ('catalog_cus_city', models.CharField(blank=True, max_length=255, null=True, verbose_name='カタログ_市区町村')),
                ('catalog_cus_banchi', models.CharField(blank=True, max_length=255, null=True, verbose_name='カタログ_番地')),
                ('catalog_cus_build', models.CharField(blank=True, max_length=255, null=True, verbose_name='カタログ_建物名')),
                ('catalog_cus_tel', models.CharField(blank=True, max_length=255, null=True, verbose_name='カタログ_電話番号')),
                ('catalog_cus_mail', models.CharField(blank=True, max_length=255, null=True, verbose_name='カタログ_メールアドレス')),
                ('bikou', models.TextField(blank=True, null=True, verbose_name='連絡事項')),
            ],
        ),
    ]
