# Generated by Django 4.2.1 on 2025-11-07 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaiko', '0007_irai_detail_irai_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='irai_detail',
            name='attention',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='注意事項'),
        ),
        migrations.AddField(
            model_name='irai_detail',
            name='bikou',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='備考'),
        ),
        migrations.AddField(
            model_name='irai_detail',
            name='cost_price',
            field=models.IntegerField(default=0, verbose_name='原価'),
        ),
        migrations.AddField(
            model_name='irai_detail',
            name='jan_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='JANコード'),
        ),
    ]
