# Generated by Django 4.2.1 on 2025-11-10 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaiko', '0008_irai_detail_attention_irai_detail_bikou_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='irai_list',
            name='shipped_com',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='運送会社'),
        ),
        migrations.AddField(
            model_name='irai_list',
            name='shipped_day',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='発送完了日'),
        ),
        migrations.AddField(
            model_name='irai_list',
            name='shipped_num',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='お問い合わせ番号'),
        ),
    ]
