# Generated by Django 4.2.1 on 2025-11-11 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaiko', '0009_irai_list_shipped_com_irai_list_shipped_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='irai_list',
            name='cancel_day',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='キャンセル日時'),
        ),
    ]
