# Generated by Django 4.2.1 on 2025-11-14 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaiko', '0010_irai_list_cancel_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='irai_list',
            name='catalog_cus_tel_search',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='カタログ_電話番号_検索用'),
        ),
    ]
